name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Create dummy .env file
        run: echo "OPENAI_KEY=dummy-key" > .env

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test